#include <Wire.h> //library for accessing I2C bus.
#define SLAVE_ADDRESS 0x04 //assigning the slave address.

int r=0;
void setup() {
    Serial.begin(9600); 
    Wire.begin(SLAVE_ADDRESS);//starting the I2C communication.
    Wire.onRequest(sendData);//sending data to the Master.
    Serial.println("Ready!");
}
void loop() {
    delay(100);
}
void sendData() {
    r=analogRead(2);//port at which resistance is connected.
    Wire.write(r/5);//scaling the value by 5 since analog value generated by Arduino is in the range of 0 to 1023 and the library can handle only upto 255.
}
